eureka:
    instance:
        client:
            serverUrl:
                defaultZone: http://localhost:8761/eureka/
spring:
    # application:
    #     name: CONFIG-PROD
    datasource:
        password: root
        url: jdbc:mysql://localhost:3306/micro_yt
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
